language: ko-KR
early_access: false

reviews:
  auto_review:
    enabled: true
    auto_incremental_review: false   # 커밋 추가(push) 시 자동 리뷰 안 함
    ignore_title_keywords:
      - "no-coderabbit"
    base_branches:
      - "develop"
      - "^feature/\\d*-.+" # `feature/숫자-`로 시작하는 브랜치만 리뷰
  high_level_summary: true           # PR 요약 생성
  sequence_diagrams: true            # 시퀀스 다이어그램 포함
  changed_files_summary: false
  estimate_code_review_effort: false # 리뷰 난이도
  poem: false