name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Docker image
        run: docker build -t tinybite-server:latest .

      - name: Save image as tar
        run: docker save tinybite-server:latest | gzip > tinybite-server.tar.gz

      - name: SCP to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "tinybite-server.tar.gz"
          target: "~/tinybite"

      - name: Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/tinybite
            docker load < tinybite-server.tar.gz
            docker-compose -f docker-compose.common.yml up -d 
            rm tinybite-server.tar.gz